version: '3.7'
services:
  wiki:
    build:
      context: .
      args:
        baseurl: "example.com"
    command: "--baseURL http://localhost:8000/"
    ports:
      - 8000:8000
    volumes:
      - .:/code